# Generated by Django 5.0.6 on 2024-06-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rows", models.PositiveIntegerField()),
                ("columns", models.PositiveIntegerField()),
                ("mines", models.PositiveIntegerField()),
                ("state", models.CharField(default="ongoing", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveIntegerField()),
                ("column", models.PositiveIntegerField()),
                ("is_mine", models.BooleanField(default=False)),
                ("is_revealed", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("adjacent_mines", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        related_query_name="cell",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveIntegerField()),
                ("column", models.PositiveIntegerField()),
                ("event", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(max_length=50)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        related_query_name="event",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cell",
            constraint=models.UniqueConstraint(
                fields=("game", "row", "column"), name="unique_cell"
            ),
        ),
    ]
